Repository suvadip172308/ui-excel, pull requests merged in 2020-01, with the labels that each got.

#16 Implemented role-based sidemenu and actions.
  src/app/components/header-navbar/header-navbar.component.html
  src/app/components/header-navbar/header-navbar.component.scss
  src/app/components/header-navbar/header-navbar.component.ts
  src/app/components/transaction-details/transaction-details.component.html
  src/app/components/transaction-details/transaction-details.component.scss
  src/app/components/transaction-details/transaction-details.component.ts
  src/app/shared/const/conts.ts
Labels: mergeable

#18 Fix for display user role issue
  src/app/reducers/login.reducer.ts
Labels: review required

#19 Bulk delete
  angular.json
  src/app/app.module.ts
  src/app/components/confirm-dialog/confirm-dialog.component.html
  src/app/components/confirm-dialog/confirm-dialog.component.scss
  src/app/components/confirm-dialog/confirm-dialog.component.spec.ts
  src/app/components/confirm-dialog/confirm-dialog.component.ts
  src/app/components/header-navbar/header-navbar.component.html
  src/app/components/header-navbar/header-navbar.component.ts
  src/app/components/operator-list/operator-list.component.html
  src/app/components/operator-list/operator-list.component.scss
  src/app/components/operator-list/operator-list.component.spec.ts
  src/app/components/operator-list/operator-list.component.ts
  src/app/components/path-list/path-list.component.html
  src/app/components/path-list/path-list.component.scss
  src/app/components/path-list/path-list.component.ts
  src/app/components/retailer-list/retailer-list.component.html
  src/app/components/retailer-list/retailer-list.component.scss
  src/app/components/retailer-list/retailer-list.component.ts
  src/app/components/transaction-list/transaction-list.component.html
  src/app/components/transaction-list/transaction-list.component.scss
  src/app/components/transaction-list/transaction-list.component.ts
  src/app/components/user-list/user-list.component.scss
  src/app/guards/login.guard.spec.ts
  src/app/guards/login.guard.ts
  src/app/routes/router.ts
  src/app/services/api/api.service.ts
  src/app/services/auth/auth.service.ts
  src/app/services/common/common.service.ts
  src/app/shared/const/conts.ts
  src/styles.scss
Labels: review required

#15 File download
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/download-file/download-file.component.html
  src/app/components/download-file/download-file.component.scss
  src/app/components/download-file/download-file.component.spec.ts
  src/app/components/download-file/download-file.component.ts
  src/app/components/header-navbar/header-navbar.component.ts
  src/app/routes/router.ts
  src/app/services/api/api.service.ts
  src/app/shared/config/config.ts
  src/app/shared/const/conts.ts
Labels: review required

#22 Path, Retailer, Trans - approve + delete
  src/app/app-routing.module.ts
  src/app/components/login/login.component.scss
  src/app/components/path-details/path-details.component.html
  src/app/components/path-details/path-details.component.scss
  src/app/components/path-details/path-details.component.ts
  src/app/components/retailer-details/retailer-details.component.html
  src/app/components/retailer-details/retailer-details.component.scss
  src/app/components/retailer-details/retailer-details.component.ts
  src/app/components/transaction-details/transaction-details.component.html
  src/app/components/transaction-details/transaction-details.component.scss
  src/app/components/transaction-details/transaction-details.component.ts
  src/app/shared/const/conts.ts
  src/styles.scss
Labels: enhancement, mergeable, review required
